parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: sapia
        connections:
            sapia:
                driver: 'oci8'
                server_version: '11.2'
                charset: al32utf8
                url: '%env(resolve:DATABASE_SAPIA_URL)%'

            fer:
                driver: 'sqlsrv'
                charset: utf-8
                user: 'fer_ro'
                password: 'trnava12'
                dbname: 'fer_stvrthodinky'
                url: '%env(resolve:DATABASE_SQLSRV_URL)%'

        types:
            mydatetime: App\Type\MyDateTimeType
