doctrine:
    orm:
        default_entity_manager: fer
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            sapia:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: sapia
                mappings:
                    Sapia:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Sapia'
                        prefix: 'App\Entity\Sapia'
                        alias: Sapia
                metadata_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                query_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                result_cache_driver:
                    type: service
                    id: doctrine.result_cache_provider
            fer:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: fer
                mappings:
                    Fer:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Fer'
                        prefix: 'App\Entity\Fer'
                        alias: Fer
                metadata_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                query_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                result_cache_driver:
                    type: service
                    id: doctrine.result_cache_provider

services:
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
